### ISSUE TITLE
Update Guest Additions Version to 4.3 version

### ISSUE THREAD

**Issue by rogeriopradoj** [jubianchi/vagrant-boxes#3]
As long as VirtualBox 4.3.x is the latest release, maybe could be a good ideia update the box to include 4.3 version.

``` shell
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default: 
    default: Guest Additions Version: 4.1.18
    default: VirtualBox Version: 4.3
```

**Comment by jubianchi** [comment]
You are right, the guest additions should be up to date.

I usually use https://github.com/dotless-de/vagrant-vbguest to automatically install the right guest additions version on VMs : dealing with guest additions is a pain, nobody uses the same vbox version.

**Comment by rogeriopradoj** [comment]
Thanks!

**Comment by jubianchi** [comment]
@rogeriopradoj The debian base box has been update to v1.0.0 with vbox guest additions. 

I'm working on doing the same thing on VMWare boxes and I'm also updating all boxes derivating from `jubianchi/debian-wheezy-chef` so they get the vbox guest addition and vmware tools.
